Repository Csaluski/cs-386-project, pull requests merged in 2021-07, with the labels that each got.

#8 Start web server using Vertx & Handlebars
  .editorconfig
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/vcs.xml
  build.gradle.kts
  build/classes/java/main/edu/nau/cs386/MainVerticle.class
  build/resources/main/static/css/mainStyle.css
  build/resources/main/static/js/index.js
  build/resources/main/templates/index.hbs
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/edu/nau/cs386/MainVerticle.java
  src/main/resources/static/css/mainStyle.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.hbs
  src/test/java/edu/nau/cs386/TestMainVerticle.java
Labels: enhancement

#17 Add my interviews
  deliverables/interviews/Interview Template.md
  deliverables/interviews/Interview Writeup Template.md
  deliverables/interviews/Saluski Guzman Interview Writeup.md
  deliverables/interviews/Saluski Hossain Interview Writeup.md
  deliverables/interviews/Saluski Kline Interview Writeup Template.md
Labels: d1

#23 D1: Finalize document
  deliverables/Inception.md
Labels: d1

#31 Jadon's parts for D2
  deliverables/deliverable2/stakeholders.md
  deliverables/deliverable2/useCaseFowler.md
  deliverables/deliverable2/userStories.md
  deliverables/deliverable2/userStoriesInKanban.png
Labels: d2

#36 Add diagram for my use case
  deliverables/deliverable2/JadonUseCaseDiagram.png
Labels: d2

#38 Add priority and difficulty to user stories
  deliverables/deliverable2/userStories.md
Labels: d2

#44 D3: add markdown description
  deliverables/deliverable3/description.md
Labels: d3

#49 Start model with dataclasses and managers
  src/main/java/edu/nau/cs386/MainVerticle.java
  src/main/java/edu/nau/cs386/Pulp.java
  src/main/java/edu/nau/cs386/manager/PaperManager.java
  src/main/java/edu/nau/cs386/manager/UserManager.java
  src/main/java/edu/nau/cs386/model/Paper.java
  src/main/java/edu/nau/cs386/model/User.java
Labels: d4

#48 D4: Add some sections and misc files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  LICENSE
  README.md
  deliverables/deliverable4/jadonParts.md
Labels: d4

#59 D4: add some more sections
  deliverables/deliverable4/jadonParts.md
Labels: d4

#77 D6: Jadon's parts
  deliverables/deliverable6/jadonParts.md
Labels: d6

#78 D6: format everything together
  deliverables/Implementation2.md
Labels: d6
